local T, C, L, G = unpack(select(2, ...))

--if G.Client ~= "zhTW" then return end

-- 共用
L["启用"] 					= "Enable"
L["加载失败"]				= "The name of s% s failed to load, please reload UI."
L["复制粘贴"]				= "Select All Ctrl+A Copy Ctrl+C Paste Ctrl+V"

L["高度"]					= "Height"
L["长度"]					= "Length"
L["字体大小"]				= "Font size"
L["大小"]					= "Size"
L["尺寸"]					= "Size"
L["纵向偏移"]				= "Vertical offset"
L["横向偏移"]				= "Horizontal offset"
L["透明度"]					= "Transparency"

L["音效"]					= "Sound effects"
L["喊话"]					= "Chat Massage"
L["标记"]					= "Raid Mark"
L["使用标记%s"]				= "Use Raid Marks %s"
L["团队框架动画"]			= "Raid Frames Animation"

-- MRT模板
L["粘贴MRT模板"]			= "Paste MRT note template"
L["MRT数据全部未找到"]		= "MRT did not find any %s note, title:%s"
L["优先级高"]				= "[High priority]"
L["反向"]					= "Reverse"
L["指定"]					= "Designated"
L["%d号位"]					= "Index %d"
L["第%d轮"]					= "Round %d"
L["所有轮次"]				= "All rounds"
L["支援技能设置"]			= "Support Skill Settings"
L["全部勾选"]				= "Check All"
L["全部取消"]				= "Cancel All"
L["添加"]					= "Add"
L["加入时间轴"]				= "The following information can be merged into the timeline"
L["MRT轮次无数据"]			= "%s[%d] no data"
L["MRT轮次分配"]			= "%s Round%d Index%s"
L["MRT该轮次数据未找到"]	= "Data for round %2$d of %1$s not found"

-- 交互宏
L["交互宏按钮"]				= "Interactive Macro Button"
L["宏"]						= "|cffFFFFFF（Macro：%s）|r"
L["点宏"]					= "Use Macro"
L["交互宏"]					= "/jst add（add me）/jst remove（remove me）"

-- 战斗记录
L["获得光环"]				= "Aura Applied %s"
L["移除光环"]				= "Aura Removed %s"
L["光环堆叠"]				= "Aura Applied Dose %s(%d)"
L["开始施法"]				= "Start Casting %s"
L["施法成功"]				= "Cast Succeeded %s"

-- NPC
L["首领"]					= "Boss"
L["杂兵"]					= "Trash"
L["传送门"]					= "Gate"

-- 职责
L["近战"]					= "Melee"
L["远程"]					= "Ranged"
L["坦克"]					= "Tank"
L["治疗"]					= "Healer"
L["近战颜色"]				= "|cffFFFF00[M]|r"
L["远程颜色"]				= "|cff00FFFF[R]|r"
L["坦克颜色"]				= "|cffD2691E[T]|r"
L["治疗颜色"]				= "|cff00FF00[H]|r"

-- 法术相关：单位
L["大怪"]					= "Big add"
L["小怪"]					= "Add"
L["BOSS强化"]				= "BOSS Buffed"
L["BOSS狂暴"]				= "BOSS Rage"
L["BOSS免疫"]				= "BOSS Immunity"
L["BOSS易伤"]				= "BOSS Vulnerable"
L["BOSS减伤"]				= "BOSS Damage Reduced"
L["阶段转换"]				= "Phase Changed"
L["召唤小怪"]				= "Summon add"
L["召唤大怪"]				= "Summon big add"
L["小怪出现"]				= "add appeared"
L["大怪出现"]				= "big add appeared"
L["远程小怪"]				= "Ranged add"
L["近战小怪"]				= "Melee add"
L["最强一波"]				= "The Strongest Wave"

-- 法术相关：模型
L["圆环"]					= "Ring"
L["大圈"]					= "Circle"
L["宝珠"]					= "Orb"
L["吐息"]					= "Breath"
L["头前"]					= "Front"
L["正负极"]					= "+/- Debuffs"
L["冲锋"]					= "Charge"
L["冲击波"]					= "Shock Wave"
L["炸弹"]					= "Bomb"
L["强力炸弹"]				= "Big Bomb"
L["爆炸"]					= "Blast"
L["飞刀"]					= "Bullet"
L["击飞"]					= "Knock off"
L["击退"]					= "Knock back"
L["钻地"]					= "Drilling"
L["拉人"]					= "Pull"
L["推人"]					= "Push"
L["近战AOE"]				= "Melee AOE"
L["射线"]					= "Ray"
L["连线"]					= "Line"
L["箭头"]					= "Arrow"
L["陷阱"]					= "Trap"

-- 法术相关：效果
L["易伤"]					= "Vulnerable"
L["减伤"]					= "Damage Reduced"
L["吸收"]					= "Absorb"
L["吸收盾"]					= "Absorb Damage"
L["吸收治疗"]				= "Absorb Healing"
L["降低血量"]				= "Max HP Reduced"
L["Buff"]					= "Buff"
L["回血"]					= "Heal"
L["DOT"]					= "DOT"
L["强力DOT"]				= "Big DOT"
L["全团AE"]					= "AOE"
L["强力AE"]					= "Big AOE"
L["流血"]					= "Bleed"
L["减速"]					= "Slow"
L["加速"]					= "Speed up"
L["心控"]					= "Mind Control"
L["致死"]					= "Heal Reduced"
L["定身"]					= "Cannot move"
L["恐惧"]					= "Fear"
L["晕眩"]					= "Dizziness"
L["昏迷"]					= "Coma"
L["沉默"]					= "Silence"
L["减急速"]					= "Reduce haste"
L["可以飞"]					= "Can fly"
L["锁定"]					= "Fixed"

-- 法术相关：应对
L["分担"]					= "Share"
L["分担伤害"]				= "Share Damage"
L["不能分担"]				= "Cant Share"
L["注意自保"]				= "Self Denfense"
L["注意治疗"]				= "Need Heal"
L["需要加满"]				= "Need Heal til full"
L["接圈"]					= "Absorb"
L["撞球"]					= "Soak orb"
L["躲球"]					= "Avoid orb"
L["躲圈"]					= "Avoid circle"
L["驱散"]					= "Dispel"
L["远离"]					= "Away"
L["靠近"]					= "Near"
L["分散"]					= "Spread"
L["集合"]					= "Gather"
L["进盾"]					= "Get In Shield"
L["引水"]					= "Bait"
L["引射线"]					= "Bait Ray"
L["点门"]					= "Portal"
L["传送"]					= "Teleport"
L["打断"]					= "Int"
L["风筝"]					= "Kite"
L["移动BOSS"]				= "Move BOSS"
L["背对BOSS"]				= "Back to BOSS"
L["躲开正面"]				= "Avoid Front"
L["靠近队友"]				= "GetClose"
L["离开人群"]				= "Get Out"
L["躲地板"]					= "Mind step"
L["快走开"]					= "Move"
L["卡视野"]					= "Block Sight"
L["停止移动"]				= "Stop moving"
L["停止施法"]				= "Stop casting"
L["不要跳"]					= "Dont jump"
L["进入内场"]				= "Enter"

-- 法术相关：警报
L["近战无人"]				= "None in melee range"
L["准备"]					= "Prepare"
L["生效"]					= "take effect"
L["安全"]					= "Safe"
L["等待"]					= "Wait"

-- 安装
L["欢迎"]					= "Welcome to JST,Please set activation rules:"
L["加载规则说明"]			= "|cFFFFFF00The newly added features are loaded according to the following rules (existing features remain unchanged):|r"
L["加载设置"]				= "Loading Rules"
L["全部禁用"]				= "Disable All"
L["指挥"]					= "RL（Enable All ）"
L["非指挥"]					= "Non-RL"
L["无"]						= "None"

L["无法导入"]				= "Wrong string, unable to import."
L["导入确认"]				= "Do you want to import all %s settings\n"
L["版本不符合"] 			= "\Version %s（Current version %s）"
L["不完整导入"] 			= "\The import may be incomplete."

-- 控制台
L["选项"]					= "Settings"
L["团队副本"]				= "Raids"
L["地下城"]					= "Dungeons"
L["更新"]					= "Update"
L["下载网址"]				= "Download URL"

L["加载规则"]				= "Loading rules"
L["导出"]					= "Export"
L["导入"]					= "Import"
L["重置设置"]				= "Reset"
L["重置所有设置"]           = "Reset All Settings "
L["解锁框体"]				= "Unlock"
L["锁定框体"]				= "Lock"
L["重载界面"]				= "Reload"

L["通用"]					= "General"
L["隐藏小地图图标"]			= "Hide the minimap icon"
L["控制台缩放"]				= "GUI Scale"
L["测试信息"]				= "Show debug massage"
L["语音包"]					= "Voice package"
L["语音包缺失"]				= "Voice package %s missing"
L["声道"]					= "Vocal tract"
L["主声道"]					= "Main vocal tract"
L["对话"]					= "Dialogue vocal tract"
L["音效"]					= "Sound effect vocal tract"
L["文本转语音"]				= "TTS"
L["文本转语音测试"]			= "TTS Test"
L["按职责加载%s"]			= "Load functions marked with %s according to current role"
L["昵称实时检测"]			= "Nickname check"
L["所有昵称已加载"]			= "Nicknames loaded successfully"
L["昵称未加载"]				= "Nickname(s) not loaded:%s"
L["多人昵称未加载"]			= "Nickname(s) not loaded:%s etc (%d)"
L["名字显示方式"]			= "Name display setting"
L["总是显示角色名"]			= "Always display character names"
L["优先显示昵称"]			= "Prioritize displaying nicknames"

L["全局禁用"]				= "Global Disable"
L["禁用插件"]				= "Disable All"
L["禁发聊天讯息"]			= "Disable Sending chat messages"
L["禁用团队标记"]			= "Disable Raid mark"
L["禁用团队框架提示"]		= "Disable Alerts on Raid Frames"
L["禁用姓名板提示"]			= "Disable Alerts on Nameplates"
L["小工具"]					= "Raid Tools"
L["团队信息"]				= "Group Information"
L["我的昵称"]		    	= "My nickname:%s"
L["输入昵称"]				= "To recognize you in the tactical board, enter your nickname. Separate multiple nicknames with spaces. Only recognize the current character name when there is no nickname."
L["刷新"]					= "Refresh"
L["昵称冲突"]				= "Nickname |cffFF0000%s|r is being used by multiple people (%s) and needs to be modified."
L["昵称错误"]				= "Nickname %s is incorrect, this person is not found in the team."
L["刷新版本和昵称"]			= "Refresh"
L["制作"]					= "Credits"
L["制作文本"]				= G.addon_name.."\n\nmade by Paopao"

-- 解锁界面
L["重置所有位置"]           = "Reset all positions"
L["重置位置确认"] 			= "Do you want to reset the position of all frames?"
L["框体的"]                 = "Frame's"
L["对齐到屏幕的"]           = "Anchor to screen's"
L["中间"] 		     		= "center"
L["左"] 		     		= "left"
L["右"] 		     		= "right"
L["中"]						= "middle"
L["上"] 		     		= "up"
L["下"] 		     		= "down"
L["前"] 		     		= "front"
L["后"]						= "back"
L["左上"] 		     		= "top left"
L["右上"] 		     		= "top right"
L["左下"] 		     		= "bottom left"
L["右下"] 		     		= "bottom right"

-- 团队标记
L["团队标记提示"]		 	= "Raid mark alert"
L["当前标记"]				= "Raid mark: %s"

-- 动态战术板
L["动态战术板"]				= "Dynamic timeline board"
L["个人战术板"]				= "Get information from personal note"
L["团队战术板"]				= "Get information from team note"
L["提前时间"]				= "Dynamic timeline board prompt time range (seconds)"
L["显示战术板时间"]			= "Display timeline board time"
L["高亮我的技能目标"]	    = "Mark my spell target on the raid frames"
L["显示计时条"]		 		= "Display timing bar"
L["计时条时间"]		    	= "Timing bar advance time"
L["朗读与我相关的内容"]	    = "TTS content related to me"
L["语音提示音量"]		    = "TTS volume"
L["语音提示时间"]		    = "TTS advance time"

L["文字提示与我相关的内容"]	= "Text prompts content related to me"
L["文字提示时间"]			= "Text prompt advance time"
L["显示秒数"]				= "Display seconds number"
L["个人战术板模板"]			= "MRT Timeline Template"
L["MRT技能模板"]			= "MRT Spell Template"
L["运行时间"]				= "Running time"
L["时间轴"]					= "Timeline"
L["战斗结束"]				= "End"

-- 法术请求
L["请求技能"]				= "Request spell alert"
L["接收法术请求"]			= "Receive spell requests from teammates"
L["提示音"]					= "Sound"
L["音效电话"]				= "Sound effect Phone"
L["音效水滴"]				= "Sound effect droplet"
L["音效铃声"]				= "Sound effect ringtone"
L["朗读请求内容"]			= "TTS"
L["请求技能提示"]			= [[|cFFFF0000*|rMacro format：
Request a spell from a teammate:/jst name spell10060
Request a spell from current target:/jst %t spell10060
Name can be changed to nickname.
10060 can be changed to other spell IDs.]]
L["法术请求格式错误"]		= "Spell request format error."
L["法术请求目标不在队伍中"] = "Spell request error:The target is not in the team"
L["法术请求玩家不在队伍中"]	= "Spell request error:%s is not in the team"
L["法术请求无法术"]			= "Spell request error:Spell ID is not recognized"
L["法术请求法术ID错误"]		= "Spell request error:Spell ID %s error"
L["法术请求已发送"]			= "Spell request sent to %s:%s"
L["收到法术请求"]			= "Received spell request from %s:%s"

---	团队 Private Auras
L["团队PA光环"]				= "Raid Private Aura Monitoring"
L["单个框架宽度"]			= "Single frame width"
L["单个框架高度"]			= "Single frame height"	
L["图标个数"]				= "Number of icons"

-- AlertIcon
L["图标提示"]				= "Icon alert"
L["图标提示2"]				= "Icon alert 2"
L["图标大小"] 				= "Icon size"
L["图标间距"]				= "Icon spacing"
L["大字体大小"]				= "Duration and stack number"
L["小字体大小"]				= "Name and tip font size"
L["显示法术时间"]			= "Display duration number"
L["排列方向"]               = "Arrangement direction"
L["向左延申"]				= "Extend icons to the left"
L["向右延申"]				= "Extend icons to the right"
L["向上延申"]				= "Extend icons to the up"
L["向下延申"]				= "Extend icons to the down"
L["PA图标提示"]				= "Private Auras Icon"
L["倒数"]					= "Countdown |cFF4169E1%d|rs"
L["层数大于"]				= "Stack more than|cFF4169E1%s|r"
L["层数小于"]				= "Stack less than|cFF4169E1%s|r"
L["层数变化"]				= "Stack changed"
L["图标%s"]					= "Icon %s %s"
L["对我施法"]				= "Casting on me"

-- AlertTimerbar
L["计时条提示"]				= "Timing bar alert"
L["计时条%s"]				= "Timing bar %s %s"

-- TextAlert
L["文字提示"]			    = "Text Alert"
L["文字提示2"]			    = "Text Alert 2"
L["血量提示"]				= "Health Text Alert"
L["血量"]					= " %.1f/%d"
L["血量2"]					= " %%.1f/%d"
L["能量提示"]				= "Power Text Alert"
L["能量"]					= " %d/%d"
L["能量2"]					= " %%d/%d"
L["技能提示"]				= "Spell Text Alert"
L["倒计时"]					= "count down"

-- RFIcon
L["团队框架提示"]			= "Raid frame alert"
L["法术图标"]				= "Spell Icon"
L["团队序号"]				= "Index Number"
L["团队框架图标%s"]			= "Raid frame icon %s"

-- PlateAlert]
L["姓名板提示"]				= "Nameplate alert"
L["垂直距离"]			    = "Vertical distance (square icon above)"
L["水平距离"]			    = "Horizontal distance (circular icon on the right)"
L["预备打断音效"]			= "Prepare to interrupt the sound effect"
L["打断音效"]				= "Interrupt sound effects"
L["打断音效语音"]			= "Interrupt sound"
L["姓名板打断图标提示"]		= [[|cFFFF0000*|rInterrupt icon MRT tactical note format：#Interruptxx-NpcID-Count-Raidmark (PlayerA)(PlayerB PlayerC)
eg1:#InterruptADD-97269-4- (|cffcc6819PlayerA|r )(|cff2133ddPlayerB|r|cffff9b00PlayerC|r )(|cffb2050fPlayerD|r)(|cffc18ef2PlayerE|r|cffffffffPlayerF|r)
eg2:#InterruptADD2-97269-2-{rt1} (|cffcc6819PlayerE|r )(|cff2133ddPlayerF|r|cffff9b00PlayerG|r)

If the MRT tactical note is not written, only the number will be displayed. After writing the tactical note, the player names can also be displayed. Click on the small gear button to show detail settings and copy the tactical note template, which can assign multiple people to be responsible for the same task at the same time.]]
L["打断模板"]				= "Interrupt %s's %s"
L["只显示我负责的打断"]		= "Only show interruptions that I am responsible for"
L["姓名板法术图标"]			= "Nameplate spell icon %s"
L["显示姓名板能量图标"]     = "Nameplate energy icon %s"
L["显示姓名板动画边框"]		= "Nameplate animation border %s"
L["显示姓名板图标打断"]		= "Nameplate Interrupt number %s"
L["自动分配打断"]			= "Automatically allocate interrupt %s"
L["显示姓名板图标光环层数"] = "Nameplate stack aura icon %s"
L["无MRT设置的循环次数"]	= "Cycle times(without MRT tactical note)"
L["忽略标记"]				= "Ignore raid marks"
L["MRT循环次数%d"]			= "%d-time-Cycle"
L["自动分配"]				= "Automatic Assign"
L["设置焦点"]				= "Set Focus"

-- Sound
L["获得光环音效"]			= "Aura applied sound %s"
L["移除光环音效"]			= "Aura removed sound %s"
L["层数增加音效"]			= "Aura applied dose sound %s"
L["开始施法音效"]			= "Spell casting start sound %s"
L["施法成功音效"]			= "Spell casting succeeded sound %s"
L["召唤小怪音效"]			= "Summon add sound %s"
L["受到伤害音效"]			= "Receive damage sound %s"

-- PhaseChangeData
L["转阶段技能"]				= "P%s %s"
L["加入战斗"]				= "%s entering combat"

-- HP_Watch
L["保命技能"]				= "Defensive spell alert"
L["注意自保血量"]			= "Denfense HP:%d%%"

-- BossMod
L["首领模块"]				= "Boss Mod"
L["职责加载"]				= "|cffFFFFFFRole|r"
L["职责加载tip"]			= "Suggest enabling according to one's own role (tank/dps/healer)"
L["RL加载"]                 = "|cffFFFFFFRL|r"
L["RL加载tip"]              = "Suggest RL to enable it"
L["所有人加载"]				= "|cffFFFFFFEveryone|r"
L["所有人加载tip"]			= "Suggest everyone to enable it"
L["技能分配加载"]			= "|cffFFFFFFAssign|r"
L["技能分配加载tip"]		= "Suggest players assigned to the spell to enable"

L["显示名字方式"]			= "Name Display Mode"
L["不显示"]					= "None"
L["只显示我的名字"]			= "Only mine"
L["全部显示"]				= "All"

L["提示方式"]				= "Prompt format"
L["计时圆圈"]				= "Timing Circle"
L["射线示意图"] 			= "Ray pattern"

L["NAME小怪标记"]			= "Mark %s，use marks %s"
L["NAME焦点自动标记"]		= "Mark %s as focus target"
L["已标记%s"]				= "%s marked %s %s。"
L["标记"] 					= "mark"

L["NAME小怪血量"]			= "Show %s's health bar"

L["NAME吸收盾"]				= "Show %s's remaining absorption capacity"

L["NAME多人光环提示"]		= "Raid debuff monitor：%s"
L["NAME换坦技能提示"]		= "Tank debuff timing bar：%s"
L["NAME多人光环层数提示"]	= "Raid debuff monitor：%s（aura stack）"
L["NAME多人光环数值提示"]	= "Raid debuff monitor：%s（effect value）"

L["NAME点名排序"]			= "assign players for %s"
L["NAME点名位置分配"]		= "assign players' spot for %s "
L["NAME示意图"]				= "%s's map"
L["使用宏%d"]				= "Use macro /jst add%s"
L["收到点名讯息"]			= "Received %s with %s applied"
L["收到移除讯息"]			= "Received %s with %s removed"
L["显示序号"]				= "Show index"
L["需要给技能%s"]			= "%s[%d] %d %s request for spell: %s"

L["NAME技能轮次安排"]		= "Assign players for %s for each round by MRT notes."
L["循环"]					= "Loop"
L["不循环"]					= "Non-loop"

L["NAME计时条"] 		 	= "Timing bar：%s"

L["NAME血量对比"]			= "Health 比较"
L["领先"]					= "Ahead by %.1f%%"
L["落后"]                   = "Behind by %.1f%%"
L["持平"]					= "Equal"

L["NAME站位分配"]			= "%s"
L["站位%d"]					= "spot %d"
L["站位序号"]				= "spot index"


L["NAME驱散提示"]			= "Use /jst dispel telling healers need to dispel %s.When healers recived it, display animation on raid frames."
L["NAME驱散提示2"]			= "Use /jst dispel telling healers need to dispel %s.When healers recived it, display animation on raid frames.You can also set an automatic prompt to dispel after n seconds."
L["自动提示驱散"]			= "Automatic prompt to dispel"
L["自动提示驱散延迟"]		= "Automatic prompt to dispel delay"
L["驱散讯息有光环"]			= "Received %s's dispel request with %s, display animation on raid frames."
L["驱散讯息序号过滤"]		= "Received %s's dispel request with %s, not accepted index, ignore."
L["驱散讯息无光环"]			= "Received %s's dispel request without %s, ignore."
L["到位后驱自己"]			= "Dispel yourself in place"
L["到位后点宏"]				= "Use Macro in place"
L["收到驱散请求"]			= "Received dispel request"
L["即将被驱散"]				= "Will be dispeled soon"
L["快驱散"]					= "Dispel now"

L["NAME自动分配减伤"]		= "Auto assign defense cooldowns for %s"